Implemented text on a path SVG element
cduck/drawSvg pull request #22
Opened 2020-09-23 14:16 UTC by marekyggdrasil

Regarding issue https://github.com/cduck/drawSvg/issues/21

Let me know if you like anything done differently. I modified README to add an example.

2020-09-24 19:28 UTC, cduck requested changes
Thanks for contributing.  The `TextOnPath` class works fine for a standalone implementation, but to integrate with the package, I would rather you add a `path=` argument to `Text`.  Can you see if it's possible to make all the current text alignment options work on a path?  (x and y could be an offset instead of an absolute position.)  If this turns out to be too complex then the current solution is good.

2020-09-24 19:28 UTC, cduck commented on README.md
> +[![Example output image](https://raw.githubusercontent.com/cduck/drawSvg/master/examples/example8.png)](https://github.com/cduck/drawSvg/blob/master/examples/example8.svg)
For browser and GitHub sanitize compatibility use the rasterized PNG (but keep the SVG in the examples folder).

2020-09-24 19:28 UTC, cduck commented on README.md
> +path.M(50, 100-50).C(100, 100-0, 200, 100-100, 250, 100-50)
`100-50` -> `50`

No need to include the math when not comparing to an SVG example.

2020-09-24 19:28 UTC, cduck commented on README.md
> +d.setRenderSize(400)
No need to set width to 400 when the default is already a reasonable 300.

2020-09-24 19:28 UTC, cduck commented on drawSvg/elements.py
> +        SVG node e.g. fill="red", font_size=20, text_anchor="middle". '''
`font_size=20` won't work because it's already a positional argument.

2020-09-24 19:28 UTC, cduck commented on drawSvg/elements.py
> +    ''' TextOnPath
No need to include the class name here.  Just give a one-line description like "Text with each character placed along the curve of a given path."

2020-10-04 03:54 UTC, marekyggdrasil commented
Some progress

```python
path = draw.Circle(stroke='lightblue', fill='white')
path.M(50, 100-50).C(100, 100-0, 200, 100-100, 250, 100-50)
d.append(path)

x = 150
y = 50
text = draw.Text('Text on a path.', 24, x=x, y=y, path=path, center=False)
```

![example8](https://user-images.githubusercontent.com/8202674/95006399-c222e700-0636-11eb-9661-c41be2d1e4bf.png)

```python
path = draw.Circle(stroke='lightblue', fill='white')
path.M(50, 100-50).C(100, 100-0, 200, 100-100, 250, 100-50)
d.append(path)

x = 150
y = 50
text = draw.Text('Text on a path.', 24, x=x, y=y, path=None, center=True)
```

![example8](https://user-images.githubusercontent.com/8202674/95006412-df57b580-0636-11eb-9250-8bc203de989d.png)

We should also consider adding `textPath`-specific attributes, especially `startOffset` and `side` seem very important, at least to me.
https://www.w3.org/TR/SVG/text.html#TextPathAttributes

But before that, first need to resolve an issue, I noticed that as long as we provide a manually defined `path` it works well, but if we provide say, a circle then it does not work

```python
path = draw.Circle(150, 50, 45, stroke='lightblue', fill='white')
d.append(path)

x = None
y = None
text = draw.Text('Text on a path.', 24, x=x, y=y, path=path, center=False)
```

![example8](https://user-images.githubusercontent.com/8202674/95006515-05318a00-0638-11eb-8398-768153b3404e.png)

2020-10-05 23:33 UTC, cduck commented
Good progress.  What is the second output supposed to be?  I would expect the text to follow the path but centered between the two ends.

I don't think SVG supports text on a `<circle>` element, only on a path representing a circle.

2020-10-06 13:27 UTC, marekyggdrasil commented
Well I think it should support it...

<img width="809" alt="Screenshot 2020-10-06 at 9 26 34 PM" src="https://user-images.githubusercontent.com/8202674/95207636-a710cc80-081a-11eb-841d-9b8012df6832.png">

ref: https://www.w3.org/TR/SVG/text.html#TextPathAttributes

2020-10-06 14:12 UTC, cduck commented
That documentation says "a path referencing a circle".  I assume this means a path element with two A commands (the A command draws an elliptical arc).  Otherwise how do you control the start point?

If you want, you could add an additional feature to here that (implicitly or explicitly) converts any supported shape into a path to make your example above work.

2020-10-09 09:19 UTC, marekyggdrasil commented
@cduck I implemented attributes specific to `textpath` tag, however I see that the built-in `rasterize` function does not necessarily support them, see the example below:

```python
import drawSvg as draw

len_x = 300
len_y = 300

d = draw.Drawing(len_x, len_y, origin='center', displayInline=False)

r = 50

cx = len_x/4
cy = len_y/4

ix = cx-r
iy = cy

fx = cx+r
fy = cy

d.append(draw.Circle(ix, iy, 1, stroke='green'))
d.append(draw.Circle(cx, cy, 1, stroke='red'))
d.append(draw.Circle(fx, fy, 1, stroke='blue'))

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

x = None
y = None

text = draw.Text('just some text', 10, x=x, y=y, path=path)
d.append(text)

cx = -len_x/4
cy = len_y/4

ix = cx-r
iy = cy

fx = cx+r
fy = cy

d.append(draw.Circle(ix, iy, 1, stroke='green'))
d.append(draw.Circle(cx, cy, 1, stroke='red'))
d.append(draw.Circle(fx, fy, 1, stroke='blue'))

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

text = draw.Text('10% offset', 10, x=x, y=y, path=path, startOffset='10%')
d.append(text)

cx = len_x/4
cy = -len_y/4

ix = cx-r
iy = cy

fx = cx+r
fy = cy

d.append(draw.Circle(ix, iy, 1, stroke='green'))
d.append(draw.Circle(cx, cy, 1, stroke='red'))
d.append(draw.Circle(fx, fy, 1, stroke='blue'))

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

text = draw.Text('inside text', 10, x=x, y=y, path=path, side='right', spacing='auto', method='stretch')
d.append(text)

cx = -len_x/4
cy = -len_y/4

ix = cx-r
iy = cy

fx = cx+r
fy = cy

d.append(draw.Circle(ix, iy, 1, stroke='green'))
d.append(draw.Circle(cx, cy, 1, stroke='red'))
d.append(draw.Circle(fx, fy, 1, stroke='blue'))

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

text = draw.Text('just some centered text', 10, x=x, y=y, path=path, text_anchor='middle', startOffset='50%')
d.append(text)

d.setRenderSize(400)
d.rasterize()

d.saveSvg('examples/example8.svg')
d.savePng('examples/example8.png')
```

built-in `rasterize` renders:

![example8](https://user-images.githubusercontent.com/8202674/95565504-e4f83580-0a52-11eb-9f57-24db9eefbc74.png)

what I see in Firefox if I open the output svg

<img width="398" alt="Screenshot 2020-10-09 at 5 19 27 PM" src="https://user-images.githubusercontent.com/8202674/95566029-9ac38400-0a53-11eb-82d2-9db32427e495.png">

It seems like the `side` attribute has a poor browser compatibility anyway... ref: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/side

Maybe we could find some hack to make it work regardles? Like document to do path in reverse for example.

2020-10-09 15:18 UTC, cduck commented
That makes sense.  `rasterize` uses CairoSVG which only supports SVG 1.1 but it looks like `side` is only in the SVG 2 draft.

I think it would be possible to create a path with the reverse direction to simulate that but I suggest leaving that to a later PR.  Try to keep this PR focused on adding the base function of text on a path.  I suggest leaving `Circle` and `side` for follow-up PRs.

2020-10-10 08:47 UTC, marekyggdrasil commented on README.md
> +[![Example output image](https://raw.githubusercontent.com/cduck/drawSvg/master/examples/example8.png)](https://github.com/cduck/drawSvg/blob/master/examples/example8.svg)
I keep SVG in the examples directory. I reference it in the README.md just because of following exactly same markdown as other examples.

2020-10-10 08:49 UTC, marekyggdrasil commented on drawSvg/elements.py
> +    ''' TextOnPath
We decided to include `path` as an argument in the `Text`, which resolves this.

2020-10-10 08:50 UTC, marekyggdrasil commented on README.md
> +path.M(50, 100-50).C(100, 100-0, 200, 100-100, 250, 100-50)
Updated math, except for the angles everything is calculated using input variables.

2020-10-10 08:51 UTC, marekyggdrasil commented on README.md
> +d.setRenderSize(400)
Updated. Thanks.

2020-10-10 09:00 UTC, marekyggdrasil commented
@cduck let me know what you think of this example, if it is not too long etc. I decided to stay with closed path examples as we keep the `startOffset` attribute.


```python
import drawSvg as draw
import math

len_x = 300
len_y = 300

d = draw.Drawing(len_x, len_y, origin='center')

# radii of the circles
R = 85
r = 65

# x, y are None when path argument provided for Text node
x = None
y = None

# centering circles around the whole canvas
ox = 0
oy = (len_y - (R*math.sin(math.pi/6) + R + 2*r))/2

# top right circle
cx = ox + R*math.cos(math.pi/6)
cy = oy + R*math.sin(math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('text on a closed path with 10% offset', 10, x=x, y=y, path=path, startOffset='10%')
d.append(text)

# top left circle
cx = ox + R*math.cos(5*math.pi/6)
cy = oy + R*math.sin(5*math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('just some text on a closed path', 10, x=x, y=y, path=path)
d.append(text)

# bottom circle
cx = ox + R*math.cos(3*math.pi/2)
cy = oy + R*math.sin(3*math.pi/2)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('just some centered text around 50% offset', 10, x=x, y=y, path=path, text_anchor='middle', startOffset='50%')
d.append(text)

# text on an arbitrary path
ix = -len_x/3
iy = -len_y/4

path = draw.Path(stroke='red', fill='none')
path.M(ix, iy).C(-len_x/3, len_y, len_x/3, -len_y, len_x-len_x/6, len_y/2)
d.append(path)
d.append(draw.Circle(ix, iy, 1, stroke='blue'))

text = draw.Text('it can be used for any path element, including paths that are not closed', 10, x=x, y=y, path=path)
d.append(text)

d.rasterize()
```

![example8](https://user-images.githubusercontent.com/8202674/95651044-fb1cf900-0b19-11eb-8e4c-72bdd0927d40.png)

I'll be happy to make further updates based on your feedback.

2020-10-10 17:19 UTC, cduck commented
Looking good.  Did you find a way to adjust the vertical position of the text relative to the path (e.g. have the center of each character on the path)?  Or is that not possible?

I'll review the code when I have some time in the next few days.

2020-10-11 05:19 UTC, marekyggdrasil commented
That was a good question. I found a way to achieve that, basically:

1. Now `textPath` can be a regular node if no `dy` or `letter-spacing` attributes are provided
2. Otherwise it becomes a parent node and includes `tspan` as a child with `dy` and/or `letter-spacing` attributes
3. I included `letter-spacing` to work also with regular text
4. unfortunately if `letter-spacing` is provided then `text-anchor="middle"` doesn't necessarily work

```python
import drawSvg as draw
import math

len_x = 300
len_y = 300

d = draw.Drawing(len_x, len_y, origin='center')

# radii of the circles
R = 85
r = 65

# x, y are None when path argument provided for Text node
x = None
y = None

# centering circles around the whole canvas
ox = 0
oy = (len_y - (R*math.sin(math.pi/6) + R + 2*r))/2

# top right circle
cx = ox + R*math.cos(math.pi/6)
cy = oy + R*math.sin(math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('text on a closed path with 10% offset and increased letter spacing', 10, x=x, y=y, path=path, startOffset='10%', letter_spacing=1.5)
d.append(text)

# top left circle
cx = ox + R*math.cos(5*math.pi/6)
cy = oy + R*math.sin(5*math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('just some text on a closed path', 10, x=x, y=y, path=path)
d.append(text)

# bottom circle
cx = ox + R*math.cos(3*math.pi/2)
cy = oy + R*math.sin(3*math.pi/2)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('just some centered text around 75% offset', 10, x=x, y=y, path=path, text_anchor='middle', startOffset='75%', dy=7)
d.append(text)

# text on an arbitrary path
ix = -len_x/3
iy = -len_y/4

path = draw.Path(stroke='red', fill='none')
path.M(ix, iy).C(-len_x/3, len_y, len_x/3, -len_y, len_x-len_x/6, len_y/2)
d.append(path)
d.append(draw.Circle(ix, iy, 1, stroke='blue'))

text = draw.Text('it can be used for any path element, including paths that are not closed', 10, x=x, y=y, path=path, dy=7)
d.append(text)

text = draw.Text('this is just a regular text without any path', 10, x=0, y=len_y/2-10, text_anchor='middle')
d.append(text)

text = draw.Text('regular text with increased letter spacing', 10, x=0, y=-len_y/2+7, text_anchor='middle', letter_spacing=1.25)
d.append(text)

d.rasterize()
```

![example8](https://user-images.githubusercontent.com/8202674/95670975-5b687500-0bc4-11eb-8ca5-c24e005c2baa.png)

2020-11-02 06:49 UTC, marekyggdrasil commented
@cduck if you are not available for the review perhaps we should convert this PR into a draft?

2020-11-03 02:09 UTC, cduck requested changes
Thanks for the reminder.  I shouldn't have left this for so long.  I really appreciate your help on the project.

I have a lot of minor suggestions but overall it looks pretty good.  The main thing I noticed when trying it out is this implementation doesn't handle the `center` argument or multi-line text.

When `center=True`, I would expect it to default to `text_anchor='middle'`, `startOffset='50%'`, and an appropriate `emOffset` (only for each that isn't specified).

I checked multi-line text on a path is supported by SVG.  Just make sure the `tspan`s added on line 436 are put in the `textPath` tag instead of the parent `text` tag.

2020-11-07 03:19 UTC, marekyggdrasil commented on README.md
> +text = draw.Text('text on a closed path with 10% offset and increased letter spacing', 10, x=x, y=y, path=path, startOffset='10%', letter_spacing=1.5)
Prepared a Flake8 linter config and updated line lengths

2020-11-07 03:20 UTC, marekyggdrasil commented on drawSvg/elements.py
> +                 lineHeight=1, path=None, startOffset=0, letter_spacing=None, **kwargs):
Line lengths updated

2020-11-09 13:55 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            else:
nice one! updated! thanks!

2020-11-09 13:58 UTC, marekyggdrasil commented on drawSvg/elements.py
> +        super().__init__(x=x, y=-y, font_size=fontSize, letter_spacing=letter_spacing, **kwargs)
Updated, thanks!

2020-11-09 14:04 UTC, marekyggdrasil commented on drawSvg/elements.py
> +        self.escapedText = xml.escape(text)
Good call. Removed.

2020-11-09 14:56 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            self.append(_TextPathNode(self.escapedText, path, letter_spacing=letter_spacing, startOffset=startOffset, **kwargs))
The `letter_spacing` should apply to both `text` and `textPath` tags.

The only attribute currently implemented that apply only for `textPath` is: `startOffset`

2020-11-09 15:00 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            outputFile.write(self.escapedText)
You mean, undo this change and instead just keep initiate `self.escapedText = None` so that `outputFile.write(self.escapedText)` gets called with `None`?

2020-11-09 15:20 UTC, cduck commented on drawSvg/elements.py
> +            outputFile.write(self.escapedText)
Actually I think `= ''` (the same as what Text does).

2020-11-10 08:29 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            self.append(TSpan(self.escapedText, dy=self.dy, letter_spacing=self.letter_spacing, **kwargs))
Updated, thanks!

2020-11-10 08:32 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            self.append(TSpan(self.escapedText, dy=self.dy, letter_spacing=self.letter_spacing, **kwargs))
Updated.

2020-11-10 08:38 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            self.append(_TextPathNode(self.escapedText, path, letter_spacing=letter_spacing, startOffset=startOffset, **kwargs))
Updated.

2020-11-10 08:41 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            outputFile.write(self.escapedText)
You mean

```python
if self.path  = '':
```

?

I'm not sure I follow... The goal of checking if path is defined here is following the structure of SVG XML tree that defines the `textPath` in case if `path` argument is defined. In this case `text` element does not contain the text but instead if contains a child `textPath` node element that contains the text.

2020-11-10 08:43 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            self.append(_TextPathNode(self.escapedText, path, letter_spacing=letter_spacing, startOffset=startOffset, **kwargs))
Done!

2020-11-10 08:45 UTC, marekyggdrasil commented on drawSvg/elements.py
> +        outputFile.write(self.escapedText)
I am not really sure how does `TSpan` help here. Wouldn't it create a child node in the SVG tree and break the structure I am trying to establish?

2020-11-10 16:27 UTC, cduck commented on drawSvg/elements.py
> +            outputFile.write(self.escapedText)
All I'm saying is if escapedText is set to the empty string, then the write function will do nothing.

2020-11-10 16:31 UTC, cduck commented on drawSvg/elements.py
> +        outputFile.write(self.escapedText)
The code does what we want but in a confusing way: "if this random attribute is set, don't write any content".  If you just set encodedText to None or the empty string in `__init__` I think it's more clear.

2020-11-10 16:33 UTC, cduck commented on drawSvg/elements.py
> +        outputFile.write(self.escapedText)
Using TSpan when the text is a single line is optional and I'll leave the choice up to you.

2020-11-14 05:32 UTC, marekyggdrasil commented on drawSvg/elements.py
> +        outputFile.write(self.escapedText)
I cleaned-up a little bit. I can see how my implementation of this logic might be confusing but at same time I don't see clearly how `TSpan` makes is simpler. Let me know what you think of current version.

Regarding the multi-line texts on paths, still working on it.

2020-11-14 05:32 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            self.append(TSpan(self.escapedText, dy=self.dy, letter_spacing=self.letter_spacing, **kwargs))
Please refer to [this comment](https://github.com/cduck/drawSvg/pull/22#discussion_r523379761). Resolving here.

2020-11-14 05:35 UTC, marekyggdrasil commented on drawSvg/elements.py
>                      kwargs['transform'] = translate
Would you like to take care of it in this PR or leave it for another PR? Since we are updating the `Text` node I think it is a great chance to clean-up a bit and make such improvements.

2020-11-14 05:36 UTC, marekyggdrasil commented on README.md
> +fy = cy
Got it, I will update with constants but it will do it after everything else is ready to merge, as it is now makes it possible for me to easily modify the example just in case if it will be required.

2020-11-14 06:29 UTC, marekyggdrasil commented
@cduck please take a look at solution for multi-line texts on path I propose

1. if text is given as iterable and path is also an iterable, it will put each line on own path (good for circles)
2. if text is just a text containing `\n` character and path is not an iterable, it will use `translate` transformation to shift the path by font size in y-direction

example:

```python
text = draw.Text(
    [
        'just some text on a closed path worth with multiple',
        'lines, each given own path'],
    10, path=[
        path,
        nested_path])
d.append(text)
```

and 

```python
text = draw.Text('it can be used for any path element, including paths that are not closed\nand automatically shifts the path for consecutive lines', 10, path=path, dy=7)
d.append(text)
```

looks good in Firefox

<img width="315" alt="Screenshot 2020-11-14 at 2 24 12 PM" src="https://user-images.githubusercontent.com/8202674/99141348-978c6b00-2685-11eb-802c-d0c554524afb.png">

but CairoSVG unfortunately is not capable of properly rendering it

![example8](https://user-images.githubusercontent.com/8202674/99141363-ac68fe80-2685-11eb-8a97-e4a7dc66a3ec.png)

looking forward to hear your comments!

2020-11-14 06:29 UTC, marekyggdrasil commented on drawSvg/elements.py
> +        outputFile.write(self.escapedText)
written a [comment with few examples](https://github.com/cduck/drawSvg/pull/22#issuecomment-727154239) for multiline texts on paths

2020-11-15 23:22 UTC, cduck commented
Nice.  I think the misaligned text by CairoSVG is caused by some bug/limitation in CairoSVG and unnecessary use of `transform`s.  Also, while testing the API with different arguments, I got some errors.

You didn't give the code for your last example so I used
```python
draw.Text(['just some centered text', 'on a closed path', 'more text'],
          10, dy=0, path=path, center=True)  # KeyError if `dy` is not given
```

Your code produces
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     width="300" height="300" viewBox="-150.0 -150.0 300 300">
<defs>
<path d="M-138.6121593216773,-63.74999999999999 A65,65,90,1,1,-8.612159321677296,-63.74999999999999 A65,65,90,1,1,-138.6121593216773,-63.74999999999999" stroke="lightblue" fill="none" id="d0" />
</defs>
<use xlink:href="#d0" />
<circle cx="-138.6121593216773" cy="-63.74999999999999" r="1" stroke="blue" />

<text x="0" y="0" font-size="10" dy="0" text-anchor="middle">
    <textPath xlink:href="#d0" dy="0" transform="translate(0,0)" startOffset="0">
        <tspan dy="0" transform="translate(0,0)">just some centered text</tspan>
    </textPath>
    <textPath xlink:href="#d0" dy="10" transform="translate(0,10)" startOffset="0">
        <tspan dy="10" transform="translate(0,10)">on a closed path</tspan>
    </textPath>
    <textPath xlink:href="#d0" dy="20" transform="translate(0,20)" startOffset="0">
        <tspan dy="20" transform="translate(0,20)">more text</tspan>
    </textPath>
</text>

</svg>
```
Firefox:
<img width="158" alt="Screen Shot 2020-11-15 at 17 18 -0600" src="https://user-images.githubusercontent.com/2476062/99199688-dfe87d80-2798-11eb-9fb5-7191fe824e25.png">

This is the output I would expect but it doesn't give consistent results (`x="0"` aligns each line with the others):
```xml
...
<text id="test">
    <textPath xlink:href="#d0" font-size="10" text-anchor="middle" startOffset="50%">
        <tspan x="0" dy="-0.6em">just some text</tspan>
        <tspan x="0" dy="1em">on a closed path</tspan>
        <tspan x="0" dy="1em">more text</tspan>
    </textPath>
</text>
...
```
Firefox (correct):
<img width="164" alt="Firefox rendering" src="https://user-images.githubusercontent.com/2476062/99199170-32279f80-2795-11eb-9972-df463d25234f.png">
Chrome/Safari (seems to center the full width before moving each line to the left):
<img width="146" alt="Safari rendering" src="https://user-images.githubusercontent.com/2476062/99199280-d3aef100-2795-11eb-873a-5de6335242ce.png">
CairoSVG:
<img width="146" alt="Safari rendering" src="https://user-images.githubusercontent.com/2476062/99199295-fe00ae80-2795-11eb-9c59-ce599de7d841.png">

This unfortunately also gives three inconsistent results:
```xml
...
<text font-size="10" text-anchor="middle">
    <textPath xlink:href="#d0" startOffset="50%">
        <tspan dy="-0.6em">just some centered text</tspan>
    </textPath>
    <textPath xlink:href="#d0" startOffset="50%">
        <tspan dy="0.4em">on a closed path</tspan>
    </textPath>
    <textPath xlink:href="#d0" startOffset="50%">
        <tspan dy="1.4em">more text</tspan>
    </textPath>
</text>
...
```

This is the only way I've found that works:
```xml
...
<g id="test">
<text>
    <textPath xlink:href="#d0" font-size="10" text-anchor="middle" startOffset="50%">
        <tspan dy="-0.6em">just some centered text</tspan>
    </textPath>
</text>
<text>
    <textPath xlink:href="#d0" font-size="10" text-anchor="middle" startOffset="50%">
        <tspan dy="0.4em">on a closed path</tspan>
    </textPath>
</text>
<text>
    <textPath xlink:href="#d0" font-size="10" text-anchor="middle" startOffset="50%">
        <tspan dy="1.4em">more text</tspan>
    </textPath>
</text>
</g>
...
```
Firefox/Chrome/Safari/CairoSVG:
<img width="162" alt="Screen Shot 2020-11-15 at 17 14 -0600" src="https://user-images.githubusercontent.com/2476062/99199627-618bdb80-2798-11eb-9a24-b014c5540edc.png">

Hope this helps.

2020-11-16 02:46 UTC, marekyggdrasil commented
Thanks a lot @cduck, I will look into that and sorry for not sharing the full source of the example, I just wanted to save up on information pollution in the thread... Unfortunately it turned out useful this time. I will investigate.

2020-11-21 05:45 UTC, marekyggdrasil commented
@cduck I made some updates, please check at your convenience

```python
import drawSvg as draw
import math

len_x = 300
len_y = 300

d = draw.Drawing(len_x, len_y, origin='center')

# radii of the circles
R = 85
r = 65
rr = r - 10 # nested circle radius

# x, y are None when path argument provided for Text node
x = None
y = None

# centering circles around the whole canvas
ox = 0
oy = (len_y - (R*math.sin(math.pi/6) + R + 2*r))/2

# top right circle
cx = ox + R*math.cos(math.pi/6)
cy = oy + R*math.sin(math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('text on a closed path with 10% offset and increased letter spacing', 10, path=path, startOffset='10%', letter_spacing=1.5)
d.append(text)

# top left circle
cx = ox + R*math.cos(5*math.pi/6)
cy = oy + R*math.sin(5*math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)
d.append(draw.Circle(ix, iy, 1, stroke='blue'))

text = draw.Text(
    [
        'just some text on a closed path',
        'with multiple lines'],
    10, path=path)
d.append(text)

# bottom circle
cx = ox + R*math.cos(3*math.pi/2)
cy = oy + R*math.sin(3*math.pi/2)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('just some centered text around 75% offset', 10, path=path, text_anchor='middle', startOffset='75%', dy=7)
d.append(text)

# text on an arbitrary path
ix = -len_x/2
iy = -len_y/4

path = draw.Path(stroke='red', fill='none')
path.M(ix, iy).C(-len_x/4, len_y, len_x/3, -len_y, len_x-len_x/6, len_y/2)
d.append(path)
d.append(draw.Circle(ix, iy, 1, stroke='blue'))

text = draw.Text('it can be used for any path element, including paths that are not closed\nand automatically shifts the path for consecutive lines', 10, path=path, dy=1)
d.append(text)

text = draw.Text('this is just a regular text without any path', 10, x=0, y=len_y/2-10, text_anchor='middle')
d.append(text)

text = draw.Text('regular text with increased letter spacing', 10, x=0, y=-len_y/2+7, text_anchor='middle', letter_spacing=1.25)
d.append(text)

d.rasterize()
```

![example8](https://user-images.githubusercontent.com/8202674/99868706-c794ba80-2bff-11eb-881e-1213752e8b50.png)

2020-12-02 08:49 UTC, cduck reviewed
Getting better.  The core feature works but there are some final details.  Thanks for your patience.

- `dy` shifts by pixels for single line text but by em for multi-line text.
- `center=True` still causes weird misalignment and doesn't center on the path.
- Drawing normal text without keyword arguments text no longer works: `draw.Text('Text', 10, 0, 0)`

Now that the API is mostly settled, we can also look at simplifying the example.  I think your 4 or 5 examples can fit on about 20 lines of code.  Each example should emphasize what one of the arguments to `Text` does.

If you want, I can do the final touches on the PR like making sure `center` works and everything is backwards compatible.

2020-12-02 08:49 UTC, cduck commented on drawSvg/elements.py
> +            super(DrawingParentElement, self).__init__()
What you want here is `super(_Text, self).__init__()` or `DrawingParentElement.__init__(self)`.

However, a cleaner way to return Group instead of Text is to use the `__new__` method instead of hacking Text to look like a Group.

2020-12-02 08:50 UTC, cduck commented on drawSvg/elements.py
> +            super().__init__(x=x, y=-y, font_size=fontSize,
Double negative on `y`.

2020-12-04 04:41 UTC, marekyggdrasil commented
Thanks for your feedback @cduck and for offering to help out. I propose the following. Let me make a one more round of corrections and then you could give it a final touch and I'll simplify the example in parallel. If you agree for such plan please leave a "👍" under this comment.

2020-12-09 14:35 UTC, marekyggdrasil commented on drawSvg/elements.py
> +                if numLines == 1:
Resolved!

2020-12-09 14:35 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            super(DrawingParentElement, self).__init__()
Resolved!

2020-12-09 14:35 UTC, marekyggdrasil commented on drawSvg/elements.py
> +            super().__init__(x=x, y=-y, font_size=fontSize,
Resolved!

2020-12-09 15:32 UTC, marekyggdrasil commented
@cduck just finished implementing the next round of changes.

1. `dy` is in pixels but in case of multi-line text it is ignored, would that be expected behaviour? this is how I implemented it, if it is not what is required please take a look, I am not sure how to combine `dy` in pixels and em units for same element.
2. `center=True` is fixed (example and screenshot below)
3. I brought back the `x` and `y` arguments for backwards compatibility (example and screenshot below)

Let me know what do you think!

```python
import drawSvg as draw
import math

len_x = 300
len_y = 300

d = draw.Drawing(len_x, len_y, origin='center')

# radii of the circles
R = 85
r = 65
rr = r - 10 # nested circle radius

# x, y are None when path argument provided for Text node
x = None
y = None

# centering circles around the whole canvas
ox = 0
oy = (len_y - (R*math.sin(math.pi/6) + R + 2*r))/2

# top right circle
cx = ox + R*math.cos(math.pi/6)
cy = oy + R*math.sin(math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, None, None, fx, fy)
path.A(r, r, 90, None, None, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('reversed direction text on a path with 10% offset and increased letter spacing', 10, None, None, path=path, startOffset='10%', letter_spacing=1.5)
d.append(text)

# top left circle
cx = ox + R*math.cos(5*math.pi/6)
cy = oy + R*math.sin(5*math.pi/6)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)
d.append(draw.Circle(ix, iy, 1, stroke='blue'))

text = draw.Text(
    [
        'just some text on a closed path',
        'with multiple lines'],
    10, None, None, path=path)
d.append(text)

# bottom circle
cx = ox + R*math.cos(3*math.pi/2)
cy = oy + R*math.sin(3*math.pi/2)

ix = cx-r
iy = cy

fx = cx+r
fy = cy

path = draw.Path(stroke='lightblue', fill='none')
path.M(ix, iy)
path.A(r, r, 90, 1, 1, fx, fy)
path.A(r, r, 90, 1, 1, ix, iy)
d.append(path)

d.append(draw.Circle(ix, iy, 1, stroke='blue'))
text = draw.Text('just some centered text around 75% offset', 10, None, None, path=path, text_anchor='middle', startOffset='75%')
d.append(text)

# text on an arbitrary path
ix = -len_x/2
iy = -len_y/4

path = draw.Path(stroke='red', fill='none')
path.M(ix, iy).C(-len_x/2, 1.125*len_y, len_x/6, -len_y, len_x/2, len_y/4)
d.append(path)
d.append(draw.Circle(ix, iy, 1, stroke='blue'))

text = draw.Text('it can be used for any path element, including paths that are not closed\nand automatically shifts the path for consecutive lines', 10, None, None, path=path, dy=1, center=True)
d.append(text)

text = draw.Text('this is just a regular text without any path', 10, 0, len_y/2-10, text_anchor='middle')
d.append(text)

text = draw.Text('regular text with increased letter spacing', 10, 0, -len_y/2+7, text_anchor='middle', letter_spacing=1.25)
d.append(text)

text = draw.Text('backwards compatibility test', 10, 0, 0)
d.append(text)

d.rasterize()
```

![example8](https://user-images.githubusercontent.com/8202674/101650279-bf999f00-3a76-11eb-817f-e29d4108d69c.png)

2021-02-04 09:10 UTC, marekyggdrasil commented
hi @cduck ! are we planning to merge it? Let me know if anything else is required from my side.

2021-02-05 01:22 UTC, cduck commented
Yes.  Let me go through and merge the code this weekend.  Then maybe you can write a simplified version of your example for the README.

2021-02-07 03:13 UTC, cduck commented
@marekyggdrasil I changed a lot of the code but kept the core design you implemented.  I'm ready to merge it once you've taken a look.

Summary of changes:
- Removed the legacy text transform I mentioned.
- The units of dy were inconsistent so I renamed it to lineOffset.
- Changed the Group of Text workaround to use __new__ instead of hacking TAG_NAME.
- Removed your long example and put a tiny example in.  When you simplify the calculations in your example, just make a new PR.
- Added separate pathArgs and tspanArgs instead of duplicating all the arguments to all the SVG tags.

2021-02-09 04:49 UTC, marekyggdrasil commented
Thank you for handling the changes. I have reviewed them and I am ok with merging. I will make a new PR with example. Awesome work!

2021-02-09 17:07 UTC, merged

2021-02-09 17:25 UTC, cduck commented
Great.  Thanks for all your hard work and patience on this.  I just published version [1.8.1](https://pypi.org/project/drawSvg/1.8.1/).