Add a title tag
cduck/drawSvg pull request #24
Opened 2020-10-05 18:25 UTC by matthewturk

This adds a "title" tag, which can be used as described in the answer here:

https://stackoverflow.com/questions/10643426/how-to-add-a-tooltip-to-an-svg-graphic

to add a tooltip.  For instance,

```
g = draw.Group(id = f"cell_{n:02d}")
g.append(draw.Title(f"cell: {i: 2d} {j: 2d}"))
```

2020-10-05 22:24 UTC, cduck requested changes
Thanks for the pull request.  This is a good feature to add.

As it is, the new `Title` element can't be used with most of the drawing elements (e.g. `Rectangle` doesn't have an `append` method).  I suggest adding an `appendTitle` method to `DrawingBasicElement` similar to `appendAnim`.  Something like
```python
    def appendTitle(self, text, **kwargs):
        self.children.append(Title(text, **kwargs))
```

See my comments to improve code quality.

Also, please add this to the examples.  I don't think it needs its own example so I would just add a title to the rectangle in example 1 (with a code comment saying what it does).

2020-10-05 22:24 UTC, cduck commented on drawSvg/elements.py
> +class Title(TSpan):
This shouldn't be a subclass of `TSpan`.  If you don't want to duplicate code, make a private common parent class.

2020-10-07 18:59 UTC, matthewturk commented
@cduck Thanks for the comments!  I *think* I addressed everything you brought up, but I wasn't totally sure if I chose the right name for the parent class.  Does this align with what you're thinking?

2020-10-07 19:16 UTC, cduck requested changes
Thanks.  This looks good.  Just two minor changes then I'll merge it.

2020-10-07 19:16 UTC, cduck commented on drawSvg/elements.py
> +class TextContainingElement(DrawingBasicElement):
Indicate this is private by prefixing the name with an underscore: `_TextContainingElement`.

2020-10-07 19:16 UTC, cduck commented on README.md
> +r.appendTitle("Our first rectangle")
Since this isn't visible in the output, add a short comment like
```suggestion
r.appendTitle("Our first rectangle")  # Add a tooltip
```

2020-10-07 19:28 UTC, cduck commented on drawSvg/elements.py
> +    ''' A private class used for elements that have content to be written. '''
Suggested clarification:
```suggestion
    ''' A private parent class used for elements that only have plain text content. '''
```

2020-10-07 19:50 UTC, matthewturk commented
Thank you!

2020-10-07 19:55 UTC, cduck commented on drawSvg/elements.py
> +    ''' A private parent class used for elements that only have plain text content. '''
Forgot to wrap to 80 characters.

2020-10-07 19:58 UTC, matthewturk commented on drawSvg/elements.py
> +    ''' A private parent class used for elements that only have plain text content. '''
Whoops, sorry for really drawing this review out into tedium ...

2020-10-07 19:59 UTC, matthewturk commented
And with my last commit, a careless vim keystroke has included my command into the commit message.  I'm happy to either rebase and squash or whatever works for you, since I've really shown my clumsiness here.

2020-10-07 20:00 UTC, cduck commented on drawSvg/elements.py
> +    ''' A private parent class used for elements that only have plain text content. '''
No problem.  This only happens because I haven't added continuous integration to the project yet.

2020-10-07 20:01 UTC, cduck commented
I squash all PRs when I merge and usually use the PR description as the final commit message.

2020-10-07 20:03 UTC, matthewturk commented
Ah, great -- thank you for your patience.  :)

On Wed, Oct 7, 2020 at 3:01 PM Casey Duckering <notifications@github.com>
wrote:

> I squash all PRs when I merge and usually use the PR description as the
> final commit message.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cduck/drawSvg/pull/24#issuecomment-705162818>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAVXO7DSHIROGEHKLN64RLSJTCLLANCNFSM4SFA4NHQ>
> .
>

2020-10-07 20:07 UTC, merged

2020-10-07 20:11 UTC, cduck commented
Merged and published version 1.7.0 (https://pypi.org/project/drawSvg/1.7.0/).  Thanks for your help.